### PR TITLE
fix: uneven distribution #79

### LINKED ISSUE #79: Diamond inheritance in sealed traits leads to uneven distribution
**Example** trait:

```
sealed trait SealedDiamond

object SealedDiamond:
  sealed trait SubtraitA extends SealedDiamond
  sealed trait SubtraitB extends SealedDiamond
  case object Foo extends SealedDiamond
  case object Bar extends SubtraitA with SubtraitB
```

**Expected behavior**

Derived arbitrary for `SealedDiamond` generates `Foo` and `Bar` with even distribution, i.e. is equivalent to either 
`Gen.oneOf(Gen.const(Bar), Gen.const(Foo))` or `Gen.oneOf(Gen.const(Foo), Gen.const(Bar))`.

**Actual behavior**

Derived arbitrary for `SealedDiamond` generates `Foo` and `Bar` with weighted distribution, equivalent to:
`Gen.oneOf(Gen.const(Bar), Gen.const(Bar), Gen.const(Foo))`.

**Cause**

Derivation recursively iterates over the `Mirror.SumOf`-instances and those look as follows:

```
scala> summon[Mirror.SumOf[example.SealedDiamond]]
val res0:
  scala.deriving.Mirror.Sum{
    type MirroredMonoType = example.SealedDiamond;
      type MirroredType = example.SealedDiamond;
      type MirroredLabel = "SealedDiamond";
      type MirroredElemTypes = (example.SealedDiamond.SubtraitA,
        example.SealedDiamond.SubtraitB, example.SealedDiamond.Foo.type);
      type MirroredElemLabels = ("SubtraitA", "SubtraitB", "Foo")
  } = example.SealedDiamond$@291fba9
                                                                                                                                                      
scala> summon[Mirror.SumOf[example.SealedDiamond.SubtraitA]]
val res1:
  scala.deriving.Mirror.Sum{
    type MirroredMonoType = example.SealedDiamond.SubtraitA;
      type MirroredType = example.SealedDiamond.SubtraitA;
      type MirroredLabel = "SubtraitA";
      type MirroredElemTypes = example.SealedDiamond.Bar.type *: EmptyTuple.type
        ;
    type MirroredElemLabels = "Bar" *: EmptyTuple.type
  } = anon$1@367026f
                                                                                                                                                      
scala> summon[Mirror.SumOf[example.SealedDiamond.SubtraitB]]
val res2:
  scala.deriving.Mirror.Sum{
    type MirroredMonoType = example.SealedDiamond.SubtraitB;
      type MirroredType = example.SealedDiamond.SubtraitB;
      type MirroredLabel = "SubtraitB";
      type MirroredElemTypes = example.SealedDiamond.Bar.type *: EmptyTuple.type
        ;
    type MirroredElemLabels = "Bar" *: EmptyTuple.type
  } = anon$1@6149184e
```

So an `Arbitrary[SealedDiamond.Bar.type]` is added twice because it occurs twice as "leaf" of the "Mirror-Tree".

### PR DESCRIPTION
**Pull request by MartinHH**
Filter out duplicate instances of Gens that can result from diamond inheritance in sealed trait (which would lead to extra weight on the affected types).

Fixes #79

### CODE REVIEW

**Comment by MartinHH** [comment]
So far, there's just a pending unit test.

File: core/src/test/scala/io/github/martinhh/test_classes.scala [hunk 1]
```diff
@@ -539,6 +539,17 @@ object DirectRecursion:
...
+
+object SealedDiamond:
+  sealed trait SubtraitA extends SealedDiamond
+  sealed trait SubtraitB extends SealedDiamond
+  case object Foo extends SealedDiamond
+  case object Bar extends SubtraitA with SubtraitB
+
+  def expectedGen: Gen[SealedDiamond] =
+    Gen.oneOf(Gen.const(Bar), Gen.const(Foo))
+
```
Comment (MartinHH) [inline core/src/test/scala/io/github/martinhh/test_classes.scala:552]: Would make sense to also add tests for `Cogen` (probably not problematic) and `Shrink`.

Comment (MartinHH) [reply core/src/test/scala/io/github/martinhh/test_classes.scala:552]: (but not in this PR)

Comment (MartinHH) [reply core/src/test/scala/io/github/martinhh/test_classes.scala:552]: See #84 for Shrink.
